<?php

return array (
  'version' => '5.5.1',
  'title' => 'Записи',
  'type' => 'post',
  'id' => '6088943d318d9',
  'updated' => 1619563957,
  'columns' => 
  array (
    '6088958190a3d8' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Постер',
      'width' => '80',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6088958190a3d8',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Заголовок',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    'categories' => 
    array (
      'type' => 'categories',
      'label' => 'Рубрики',
      'width' => '15',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'name' => 'categories',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Дата',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
    '60889470e28f5c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Форма',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60849c392b2df',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60889470e28f5c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_filter_category' => 'off',
    'hide_filter_post_format' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);