<?php

return array (
  'version' => '5.5.3',
  'title' => 'Партнёры',
  'type' => 'partners',
  'id' => '60dba35db2573',
  'updated' => 1625006941,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Заголовок',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Дата',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
    'wpseo-score' => 
    array (
      'type' => 'wpseo-score',
      'label' => '<span class="yoast-tooltip yoast-tooltip-n yoast-tooltip-alt" data-label="Оценка SEO"><span class="yoast-column-seo-score yoast-column-header-has-tooltip"><span class="screen-reader-text">Оценка SEO</span></span></span>',
      'width' => '63',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'name' => 'wpseo-score',
    ),
    'wpseo-score-readability' => 
    array (
      'type' => 'wpseo-score-readability',
      'label' => '<span class="yoast-tooltip yoast-tooltip-n yoast-tooltip-alt" data-label="Оценка читабельности"><span class="yoast-column-readability yoast-column-header-has-tooltip"><span class="screen-reader-text">Оценка читабельности</span></span></span>',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'name' => 'wpseo-score-readability',
    ),
    'wpseo-title' => 
    array (
      'type' => 'wpseo-title',
      'label' => 'SEO заголовок',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => 'wpseo-title',
    ),
    'wpseo-metadesc' => 
    array (
      'type' => 'wpseo-metadesc',
      'label' => 'Мета описание',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'name' => 'wpseo-metadesc',
    ),
    'wpseo-focuskw' => 
    array (
      'type' => 'wpseo-focuskw',
      'label' => 'Ключевая фраза',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'name' => 'wpseo-focuskw',
    ),
    'wpseo-links' => 
    array (
      'type' => 'wpseo-links',
      'label' => '<span class="yoast-linked-to yoast-column-header-has-tooltip" data-tooltip-text="Количество внутренних ссылок в этом посте. Подробности во вкладке Помощь, "Столбцы Yoast"."><span class="screen-reader-text">Исходящие внутренние ссылки</span></span>',
      'width' => '',
      'width_unit' => '%',
      'sort' => 'on',
      'name' => 'wpseo-links',
    ),
    '60dba351cfdf3c' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Постер',
      'width' => '',
      'width_unit' => '%',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60dba351cfdf3c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);